// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlanticCity.BibliotecarioJC.InfraStructure.Models;

public partial class Estado
{
    public int IdEstado { get; set; }

    public string CodEstado { get; set; }

    public string Nombre { get; set; }

    public bool? EsActivo { get; set; }

    public string Tabla { get; set; }

    public virtual ICollection<PrestamoBitacora> PrestamoBitacoras { get; set; } = new List<PrestamoBitacora>();

    public virtual ICollection<PrestamoDetalle> PrestamoDetalles { get; set; } = new List<PrestamoDetalle>();

    public virtual ICollection<Prestamo> Prestamos { get; set; } = new List<Prestamo>();
}