// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlanticCity.BibliotecarioJC.InfraStructure.Models;

public partial class Inventario
{
    public int IdInventario { get; set; }

    public int? IdLibro { get; set; }

    public int? IdEstante { get; set; }

    public int? StockInicial { get; set; }

    public int? StockActual { get; set; }

    public bool? EsActivo { get; set; }

    public virtual Estante IdEstanteNavigation { get; set; }

    public virtual Libro IdLibroNavigation { get; set; }
}