// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlanticCity.BibliotecarioJC.InfraStructure.Models;

public partial class Prestamo
{
    public int IdPrestamo { get; set; }

    public int? IdUsuario { get; set; }

    public DateTime? FechaPrestamo { get; set; }

    public int? IdEstado { get; set; }

    public string Observacion { get; set; }

    public virtual Estado IdEstadoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }

    public virtual ICollection<PrestamoBitacora> PrestamoBitacoras { get; set; } = new List<PrestamoBitacora>();

    public virtual ICollection<PrestamoDetalle> PrestamoDetalles { get; set; } = new List<PrestamoDetalle>();
}