// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlanticCity.BibliotecarioJC.InfraStructure.Models;

public partial class PrestamoDetalle
{
    public int IdPrestamoDetalle { get; set; }

    public int? IdPrestamo { get; set; }

    public int? IdLibro { get; set; }

    public int? IdEstado { get; set; }

    public int? IdEstante { get; set; }

    public DateTime? FechaEntrega { get; set; }

    public decimal? CobroPrestamo { get; set; }

    public decimal? CobroPerdida { get; set; }

    public string Observacion { get; set; }

    public virtual Estado IdEstadoNavigation { get; set; }

    public virtual Estante IdEstanteNavigation { get; set; }

    public virtual Libro IdLibroNavigation { get; set; }

    public virtual Prestamo IdPrestamoNavigation { get; set; }
}