// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlanticCity.BibliotecarioJC.InfraStructure.Models;

public partial class PrestamoBitacora
{
    public int IdBitacora { get; set; }

    public int? IdEstado { get; set; }

    public int? IdPrestamo { get; set; }

    public DateTime? FechaOperacion { get; set; }

    public int? IdUsuario { get; set; }

    public string Observacion { get; set; }

    public virtual Estado IdEstadoNavigation { get; set; }

    public virtual Prestamo IdPrestamoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}