// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AtlanticCity.BibliotecarioJC.InfraStructure.Models;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string DocumentoIdentidad { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string Direccion { get; set; }

    public string Ubigeo { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<ListaNegra> ListaNegras { get; set; } = new List<ListaNegra>();

    public virtual ICollection<PrestamoBitacora> PrestamoBitacoras { get; set; } = new List<PrestamoBitacora>();

    public virtual ICollection<Prestamo> Prestamos { get; set; } = new List<Prestamo>();
}