FROM node:latest as build
WORKDIR /app
COPY ./ /app
RUN npm cache clean --force
RUN npm install
RUN npm run build

FROM nginx:latest
RUN apt-get update
RUN apt-get install -y locales locales-all
ENV LC_ALL es_PE.UTF-8
ENV LANG es_PE.UTF-8
ENV LANGUAGE es_PE.UTF-8
ENV TZ="America/Lima"


COPY ./nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=build /app/dist/sakai-ng /usr/share/nginx/html

EXPOSE 80
